In [1]:
import pandas as pd
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv("tips.csv")

display(df.head())
print(df.info())
display(df.describe())

fig1 = px.scatter(
    df,
    x="total_bill",
    y="tip",
    color="sex",
    title="Total Bill vs Tip by Sex"
)
fig1.show()


fig2 = px.pie(
    df,
    names="sex",
    title="Distribution of Sex"
)
fig2.show()


df_encoded = pd.get_dummies(
    df,
    columns=["sex", "smoker", "day", "time"],
    drop_first=True
)


X = df_encoded.drop("tip", axis=1)
y = df_encoded["tip"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

r2 = model.score(X_test, y_test)
print("R² Score:", round(r2, 2))

for name, coef in zip(X.columns, model.coef_):
    print(f"{name} : {round(coef, 3)}")


new_data = pd.DataFrame({
    "total_bill": [30],
    "size": [3],
    "sex_Male": [1],
    "smoker_Yes": [0],
    "day_Fri": [0],
    "day_Sat": [1],
    "day_Sun": [0],
    "time_Lunch": [0]
})


new_data = new_data.reindex(columns=X.columns, fill_value=0)

predicted_tip = model.predict(new_data)[0]
print(f"Predicted Tip: ${round(predicted_tip, 2)}")

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB
None

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

R² Score: 0.44
total_bill : 0.095
size : 0.233
sex_Male : 0.029
smoker_Yes : -0.192
day_Sat : -0.186
day_Sun : -0.051
day_Thur : -0.18
time_Lunch : 0.095
Predicted Tip: $4.11